### ISSUE TITLE
Segmentation fault in mkdir 

### ISSUE THREAD

**Issue by hsgaurav** [duskybomb/Project-shell#9]
@Eklavya42 Please check your mkdir the function shows segmentation fault error after i add my copy function to the file without even touching your function. I just included two libraries which are #include #include <time.h>
#include <fcntl.h>
and it caused me segmentation fault

**Comment by hsgaurav** [comment]
i'm trying to do it without addressing it in builtin str function

**Comment by duskybomb** [comment]
Now works
